### ISSUE TITLE
Preventing multiple connections from php subprocesses launched from php

### ISSUE THREAD

**Issue by cipher-code** [xdebug/vscode-php-debug#167] opened 2017-05-25 04:15 UTC
This line in the default WordPress phpunit setup fires off a php subprocess: https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/includes/bootstrap.php#L68

This causes multiple connections to xdebug. If you set a breakpoint on this line, the multiple connections will confuse the php-debug extension and the code wont go past that point.

There should be a configuration to set the maximum number of sessions, beyond which additional sessions get rejected. In this case, setting the maximum number of xdebug sessions to 1 should take care of this problem.

**Comment by felixfbecker** [comment] 2017-05-28 18:49
Could you clarify what you mean with "gets confused"?
What do you expect the adapter to do exactly if the limit is reached and it receives a connection?

**Comment by crackukass** [comment] 2017-07-26 16:15
I think i have the same bug : when a bp is set on a line of a source, the debuger stops on this line correctly ; but if some part of code start a new php thread on the server wich calls the same bp, the debuger freezes. 
In the call stack view, you see 2 threads : one suspended by step, the other one running and you have to stop debuger to continue.

**Comment by insprintorob** [comment] 2017-08-02 06:18
Another advantage of a feature to stop multiple connections is to prevent multiple connections from ajax requests. My application often fires off 6 or so ajax requests, which you can see as Request 1, Request 2 etc in the debug panel.

They seem to slow the debugger down.

**Comment by scottsb** [comment] 2017-10-03 14:44
I believe this is a duplicate of #164.

**Comment by zobo** [comment] 2021-05-10 09:23
I cannot reproduce this and a lot of changes were made in the last 5 years.

**Closed by zobo** 2021-05-10 09:23 UTC
Labels: needs more info
