### ISSUE TITLE
1.14.6 XDebug does not work

### ISSUE THREAD

**Issue by jmo161** [xdebug/vscode-php-debug#492] opened 2021-02-02 20:25 UTC
PHP version:  7.4.14
XDebug version:  2.9.8
Adapter version: 1.14.6

Your launch.json:  
XDebug php.ini config:

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php
<?php

echo '';
```

XDebug does not seem to even run.  None of my launch configs work - it shows the run controls at the top of VS Code briefly and then disappears.

Switching back to 1.14.5 works fine, the issue is only present in 1.14.6

**Comment by efc** [comment] 2021-02-02 20:31
I've also had to reinstall 1.14.5 to get XDebug working again. (The menu disclosure on the "Uninstall" button allows you to install an earlier version.) This issue has been marked a "duplicate", maybe @zobo can point to the issue that it is duplicating?

**Comment by wouterverweirder** [comment] 2021-02-02 20:31
I can confirm - having exactly the same issue here:
PHP version 7.3.1
Xdebug version: 3.0.2

**Comment by jtowe1** [comment] 2021-02-02 20:34
@efc https://github.com/xdebug/vscode-php-debug/issues/490

**Comment by zobo** [comment] 2021-02-02 20:37
Closing as duplicate of #490. Was fixed in #491 released as 1.14.7

**Closed** 2021-02-02 20:38 UTC
Labels: duplicate
