### ISSUE TITLE
Can't add breakpoints after VS Code version: 1.52.0

### ISSUE THREAD

**Issue by RAFA3L** [xdebug/vscode-php-debug#427] opened 2020-12-11 15:19 UTC
Few minutes ago and after update VS Code to the Version: 1.52.0 I can't add breakpoints anymore. Previous breakpoints added still working, but I can't add new one.

**Comment by dsclee1** [comment] 2020-12-11 15:49
I have the same issue.

**Comment by dsclee1** [comment] 2020-12-11 16:11
Duplicate of #424

**Comment by gentig** [comment] 2020-12-11 16:35
Same issue here, I hope it is fixed soon

**Comment by gentig** [comment] 2020-12-11 17:50
I added a comment how to fix the issue here https://github.com/felixfbecker/vscode-php-debug/issues/424#issuecomment-743334478

**Comment by YahyaAhmad** [comment] 2020-12-13 10:09
Hello, I fixed this issue temporarily by going to settings.json and adding this line:
` "debug.allowBreakpointsEverywhere": true;`

**Comment by MarkusRodler** [comment] 2020-12-14 13:41
> Hello, I fixed this issue temporarily by going to settings.json and adding this line:
> ` "debug.allowBreakpointsEverywhere": true;`

Without the trailing semicolon

**Comment by alonzo-ped** [comment] 2020-12-14 15:39
For anyone still searching, I was able to do this in the GUI by going to Settings and clicking specifically on the User settings tab, then search for debug at the top of the window. You should see:
`Debug: Allow Breakpoints Everywhere`
right at the top of the list. Just enable the checkbox.

**Comment by walachid** [comment] 2020-12-14 19:48
Hello, in my case with VSCodium, adding the line : "debug.allowBreakpointsEverywhere": true; permit to add breakpoint but they don't stop.

**Comment by kanlukasz** [comment] 2020-12-15 18:50
I can confirm:
- at WSL2 environment cannot add breakpoint too
- `"debug.allowBreakpointsEverywhere": true` helped, now i can add breakpoints

VSCode version: `1.52.0 (system setup)`

_I don't have any additional problems like not stopping on breakpoints_

**Comment by SjoerdPennings** [comment] 2020-12-17 13:00
1.52.1 seems to have fixed the issue.

**Comment by vinser** [comment] 2020-12-21 19:01
> VS Code 1.52.1 seems to have fixed the issue.

Yes! VS Code 1.52.1 fixed the issue with Subj - felixfbecker.php-debug works again, but with Xdebug version >= 3 does not work

**Comment by zobo** [comment] 2021-01-26 23:50
I believe this is resolved and should be closed.

**Closed** 2021-02-06 08:41 UTC
