### ISSUE TITLE
On large call stacks the position of the scroll bar resets periodically 

### ISSUE THREAD

**Issue by slifin** [xdebug/vscode-php-debug#98] opened 2016-11-23 10:02 UTC
To replicate this get a large enough call stack to get a scroll bar or shorten the height of the call stack window to get a scroll bar 

hover over the call stack then click one bit of the stack and wait the view will glitch to the top of the list 
it will also glitch to the top of the view periodically on its own

version: 1.10.0
vscode version: 1.7.2

**Comment by zobo** [comment] 2021-05-10 08:20
Cant reproduce, but could be a duplicate of #558.

**Closed by zobo** 2021-05-10 08:20 UTC
