### ISSUE TITLE
Step filter to skip files

### ISSUE THREAD

**Issue by jmcbee** [xdebug/vscode-php-debug#313] opened 2018-10-07 04:34 UTC
PHP version:  v7.2.6
XDebug version:  v2.6.0

Hello,

Is it possible to skip certain files when stepping over? It seems the `ignore` option is only for ignoring errors.

https://bugs.xdebug.org/view.php?id=901#bugnotes

Here's the equivalent on PHPStorm: https://www.jetbrains.com/help/phpstorm/step-filters.html

**Comment by alimuzzaman** [comment] 2019-05-03 17:56
I need, **Step Into** to skip files outside of project, and step into next line of code inside of the open project.
Or implement a new **Step Into** button.

> When debugging WordPress plugin, if we click jump into it jumps into WordPress core function do_action or apply_filters, which is hard to navigate.
What do I expect is to ignore the core function and jump into registered action or filter directly.

**Comment by jacobweber** [comment] 2021-06-27 16:49
This would be very useful, e.g. to ignore autoload when stepping into a function call.

**Comment by zobo** [comment] 2021-09-20 11:47
The issue is not that straight forward. If I want to solve this in the extension code, I would need to perform a "step in", check the path and again perform a "step in" until I landed on a path that is not ignored. The concept is called `justMyCode` (https://code.visualstudio.com/docs/python/debugging#_justmycode) . I have this feature in mind, but will discuss it with Derick first what the best option for it could be.

**Comment by Boffice** [comment] 2022-09-26 19:10
Any news on the subject ?

**Comment by zobo** [comment] 2022-09-29 21:54
No sorry, not yet. There is still no feasible way to implement this and I'm currently dealing with cloud support.

**Comment by zobo** [comment] 2022-12-28 23:28
Implemented in #874 . Will be merged and released shortly.

**Closed by zobo** 2022-12-28 23:28 UTC
