### ISSUE TITLE
Make debugger easier to configure

### ISSUE THREAD

**Issue by mousetraps** [xdebug/vscode-php-debug#142] opened 2017-02-07 06:22 UTC
Ideally there would be a way to make the debugger super easy to configure without modifying your default `php.ini` or providing a custom one. 

See the `launch.json` and `settings.json` files in the link below for my current crazy workaround to this:
https://github.com/Microsoft/tolerant-php-parser/pull/91/files

A few things to note:
* `xdebug.remote_enable=1` and `xdebug.remote_autostart=1` are set in `runtimeArgs`
* `zend_extension` is also set as a runtime argument, but because it will differ between individual PHP installs, it points to a custom workspace setting `${config.php.xdebug.extension}`
* the default value for `php.xdebug.extension` is an informative message detailing to the user what they should do to set up the debugger.

I think doing something similar in the core extension would decrease the friction required to get started with the debugger. In particular, I think it'd be helpful to:
* provide a user setting for the `zend_extension` path rather than asking people to enable it in `php.ini`. This has the additional benefit of making it easier for people to run without the debug extension by simply using `Ctrl+F5`, which results in a significant performance boost for some scenarios. 
* set `xdebug.remote_autostart` and `xdebug.remote_enable` values by default when running the debugger.

Thoughts?

**Comment by mousetraps** [comment] 2017-02-07 06:27
Also, I'm not entirely sure how well this approach would work with different versions of PHP or XDebug - hopefully there's not too much variance, but it would be worth looking into.

**Comment by felixfbecker** [comment] 2017-02-07 08:24
Very interesting idea! The problem is though that 99% of PHP developers use PHP not for CLI, but for web development. In these contexts PHP is run through a web server like Apache or nginx, and you have to modify the php.ini and then use the "Listen for XDebug" config.

So a different approach would be to provide a command with the extension that sets up your php.ini, maybe even installs XDebug automatically.

**Comment by mousetraps** [comment] 2017-02-08 00:59
@felixfbecker - Indeed, that is a challenging case to handle. What about a two-pronged approach?
* programmatically configure -d zend_extension property during launch configurations (hopefully >1% of PHP developers write tests?)
* provide better guidance during listen configuration when no "program" property is specified. It sounds like you were thinking something interactive - I would be hesitant to go the full nine yards and automatically edit the file, but what about automatically popping it up in the editor when provided with the PHP executable path? 

Also, I *really* like the idea of installing Xdebug automatically. Is PEAR/PECL the most reasonable way to handle this?

**Comment by felixfbecker** [comment] 2017-02-08 01:09
So what I don't like that much about putting `zend_extension` inside the launch.json is that it needs to be an absolute file path to the dll/so, so you can't commit that launch.json really anymore because it only works on your machine.

pecl is the best for Linux but not available on Windows. On Windows I would download the DLL and put it in the extension folder, I actually do that in CI on AppVeyor: https://github.com/felixfbecker/vscode-php-debug/blob/master/appveyor-install.ps1#L11

Travis with pecl: https://github.com/felixfbecker/vscode-php-debug/blob/master/.travis.yml#L22

**Comment by mousetraps** [comment] 2017-02-08 03:00
> So what I don't like that much about putting zend_extension inside the launch.json is that it needs to be an absolute file path to the dll/so, so you can't commit that launch.json really anymore because it only works on your machine.

Ahh, let me clarify - I meant that this would be a user-level setting rather than a setting in `launch.json`. The PR I linked to was just the better-than-nothing workaround for the time being.

> pecl is the best for Linux but not available on Windows

Hmm... Maybe I'm missing something, but I thought that some pre-built DLLS are available for Windows (including xdebug) - http://php.net/manual/en/install.windows.pecl.php. That said, I haven't *personally* tried it, so there may be some additional configuration annoyance on Windows that I'm not aware of.

The other thing I was worried about is the additional overhead of maintaining links to the relevant precompiled versions of Xdebug, but luckily it looks like the urls are relatively sane, so it shouldn't be too bad. https://xdebug.org/download.php

**Comment by felixfbecker** [comment] 2017-02-08 10:19
Hmm, this makes it pretty complicated. I would prefer the approach of modifying the php.ini.

I tried installing XDebug with PECL on Windows before, it doesn't really work. The Windows community usually just downloads DLLs, and that is easy to automate (see the CI config files).
I think we could find out the right file by POSTing the `php -i` output to https://xdebug.org/wizard.php.
Another thing that even more complicates this is that on Linux you have different php.ini files for CLI and Apache.

**Comment by kanlukasz** [comment] 2019-06-06 12:20
you can test this one: https://marketplace.visualstudio.com/items?itemName=kakumei.php-xdebug

**Comment by zobo** [comment] 2021-10-13 12:24
Interesting how I came to to roughly same conclusions... The plugin offers configuration snippets with `env` and `runtimeArgs` that trigger debugging as long as Xdebug is loaded into PHP. A `resolveDebugConfiguration` is also provided now that handles the no-folder scenario (no `launch.json` file) and a setting fallback for the location of php executable `php.executablePath`.
Helping the user via the use of https://xdebug.org/wizard.php is also planned...

I'll close this task as it is old and partially already covered.

**Closed by zobo** 2021-10-13 12:24 UTC
