### ISSUE TITLE
Eval can't return grandchildren and their younger generations

### ISSUE THREAD

**Issue by QwertyZW** [xdebug/vscode-php-debug#155] opened 2017-03-31 03:01 UTC
![bug](https://cloud.githubusercontent.com/assets/8478946/24534531/977969e0-159c-11e7-9559-06b98d877946.png)

Adapter version:  https://github.com/felixfbecker/vscode-php-debug/commit/74f566250ad565e73753eb427fd02c0ce41c4a40

Eval command can't expand grand children and anything that falls under them

E.g: from `variables.php` under testproject

`$anArray = array(1, 'test' => 2, 'test2' => ['t' => 123]);`

attempting to eval $anArray returns the array, expanding it works. but expanding test2 does not. The vscode arrow settles on the expanded state but wouldn't actually list test2's children

Problem looks like it's started here:
https://github.com/felixfbecker/vscode-php-debug/blob/master/src/xdebugConnection.ts#L485

**Comment by felixfbecker** [comment] 2017-03-31 07:19
This is likely caused by your depth settings, see `xdebugSettings`: https://github.com/felixfbecker/vscode-php-debug#supported-launchjson-settings

**Comment by QwertyZW** [comment] 2017-04-01 04:02
Tried 

```
{
  "version": "0.2.0",
  // "debugServer": 4711, // Uncomment for debugging the adapter
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
     // "log": true,
     "xdebugSettings": {
       "max_children": 100,
       "max_data": 100
     },
      "debugServer": 4711
    },
    {
      "name": "Launch",
      "request": "launch",
      "type": "php",
      "program": "${file}",
      "cwd": "${workspaceRoot}",
      "externalConsole": false
    }
  ]
}
```

and 

```
{
  "version": "0.2.0",
  // "debugServer": 4711, // Uncomment for debugging the adapter
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
     // "log": true,
     "xdebugSettings": {
       "max_children": 100,
       "max_data": 100
     },
      "debugServer": 4711
    },
    {
      "name": "Launch",
      "request": "launch",
      "type": "php",
      "program": "${file}",
      "cwd": "${workspaceRoot}",
      "externalConsole": false
    }
  ]
}{
  "version": "0.2.0",
  // "debugServer": 4711, // Uncomment for debugging the adapter
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
     // "log": true,
     "xdebugSettings": {
       "max_children": 10,
       "max_data": 10
     },
      "debugServer": 4711
    },
    {
      "name": "Launch",
      "request": "launch",
      "type": "php",
      "program": "${file}",
      "cwd": "${workspaceRoot}",
      "externalConsole": false
    }
  ]
}
```

but with no luck

**Comment by felixfbecker** [comment] 2017-04-01 07:23
I need your logs

**Comment by QwertyZW** [comment] 2017-04-01 21:32
Xdebug:
```
Log opened at 2017-04-01 21:15:37
I: Connecting to configured address/port: localhost:9000.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php" language="PHP" xdebug:language_version="7.0.4-5ubuntu1" protocol_version="1.0" appid="9057" idekey="khishman"><engine version="2.4.0"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2016 by Derick Rethans]]></copyright></init>

<- breakpoint_list -i 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="1"></response>

<- breakpoint_set -i 2 -t line -f file:///home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php -n 6
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="2" id="90570001"></response>

<- breakpoint_list -i 3
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="3"><breakpoint type="line" filename="file:///home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php" lineno="6" state="enabled" hit_count="0" hit_value="0" id="90570001"></breakpoint></response>

<- breakpoint_list -i 4
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="4"><breakpoint type="line" filename="file:///home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php" lineno="6" state="enabled" hit_count="0" hit_value="0" id="90570001"></breakpoint></response>

<- run -i 5
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="5" status="break" reason="ok"><xdebug:message filename="file:///home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php" lineno="6"></xdebug:message></response>

<- stack_get -i 6
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="6"><stack where="{main}" level="0" type="file" filename="file:///home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php" lineno="6"></stack></response>

<- context_names -i 7 -d 0
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_names" transaction_id="7"><context name="Locals" id="0"></context><context name="Superglobals" id="1"></context><context name="User defined constants" id="2"></context></response>

<- context_get -i 8 -d 0 -c 0
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_get" transaction_id="8" context="0"><property name="$anArray" fullname="$anArray" type="array" children="1" numchildren="3" page="0" pagesize="32"><property name="0" fullname="$anArray[0]" type="int"><![CDATA[1]]></property><property name="test" fullname="$anArray[&#39;test&#39;]" type="int"><![CDATA[2]]></property><property name="test2" fullname="$anArray[&#39;test2&#39;]" type="array" children="1" numchildren="1"></property></property><property name="$arrayWithSpaceKey" fullname="$arrayWithSpaceKey" type="uninitialized"></property></response>

<- eval -i 9 -- JGFuQXJyYXk=
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="eval" transaction_id="9"><property type="array" children="1" numchildren="3" page="0" pagesize="32"><property name="0" type="int"><![CDATA[1]]></property><property name="test" type="int"><![CDATA[2]]></property><property name="test2" type="array" children="1" numchildren="1"></property></property></response>

<- context_get -i 10 -d 0 -c 0
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_get" transaction_id="10" context="0"><property name="$anArray" fullname="$anArray" type="array" children="1" numchildren="3" page="0" pagesize="32"><property name="0" fullname="$anArray[0]" type="int"><![CDATA[1]]></property><property name="test" fullname="$anArray[&#39;test&#39;]" type="int"><![CDATA[2]]></property><property name="test2" fullname="$anArray[&#39;test2&#39;]" type="array" children="1" numchildren="1"></property></property><property name="$arrayWithSpaceKey" fullname="$arrayWithSpaceKey" type="uninitialized"></property></response>

<- stop -i 11
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="11" status="stopped" reason="ok"></response>

-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="11" status="stopping" reason="ok"></response>

Log closed at 2017-04-01 21:15:57

```

A manually put together Debug console(Don't know how to copy the whole thing in one go or get vscode to dump it, making this quite the chore)

```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }
new connection 1
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 1 } }
<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }
-> threadsRequest
{ command: 'threads', type: 'request', seq: 3 }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (17:15:37)' } ] } }
-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments: 
   { source: 
      { path: '/home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php',
        name: 'variables.php' },
     lines: [ 6 ],
     breakpoints: [ { line: 6 } ],
     sourceModified: false },
  type: 'request',
  seq: 4 }
<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 4,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 6 } ] } }
-> setFunctionBreakpointsRequest
{ command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 5 }
<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 5,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] } }
-> setExceptionBreakpointsRequest
{ command: 'setExceptionBreakpoints',
  arguments: { filters: [] },
  type: 'request',
  seq: 6 }
<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 6,
  command: 'setExceptionBreakpoints',
  success: true }
-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 7 }
-> threadsRequest
{ command: 'threads', type: 'request', seq: 8 }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 8,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (17:15:37)' } ] } }
<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 7,
  command: 'configurationDone',
  success: true }
<- stoppedEvent
StoppedEvent {
  seq: 0,
  type: 'event',
  event: 'stopped',
  body: { reason: 'breakpoint', threadId: 1, allThreadsStopped: false } }
-> threadsRequest
{ command: 'threads', type: 'request', seq: 9 }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 9,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (17:15:37)' } ] } }
-> stackTraceRequest
{ command: 'stackTrace',
  arguments: { threadId: 1, startFrame: 0, levels: 20 },
  type: 'request',
  seq: 10 }
<- stackTraceResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 10,
  command: 'stackTrace',
  success: true,
  body: 
   { stackFrames: 
      [ { id: 1,
          name: '{main}',
          source: 
           { name: 'variables.php',
             path: '/home/khishman/dev/vsextensions/vscode-php-debug/testproject/variables.php' },
          line: 6,
          column: 1 } ] } }
-> scopesRequest
{ command: 'scopes',
  arguments: { frameId: 1 },
  type: 'request',
  seq: 11 }
<- scopesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 11,
  command: 'scopes',
  success: true,
  body: 
   { scopes: 
      [ Scope { name: 'Locals', variablesReference: 1, expensive: false },
        Scope { name: 'Superglobals', variablesReference: 2, expensive: false },
        Scope {
          name: 'User defined constants',
          variablesReference: 3,
          expensive: false } ] } }
-> variablesRequest
{ command: 'variables',
  arguments: { variablesReference: 1 },
  type: 'request',
  seq: 12 }
<- variablesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 12,
  command: 'variables',
  success: true,
  body: 
   { variables: 
      [ { name: '$anArray',
          value: 'array(3)',
          type: 'array',
          variablesReference: 4 },
        { name: '$arrayWithSpaceKey',
          value: 'uninitialized',
          type: 'uninitialized',
          variablesReference: 0 } ] } }
$anArray
array(3)
0:1
test:2
test2:array(1)
-> evaluateRequest
{ command: 'evaluate',
  arguments: { expression: '$anArray', frameId: 1, context: 'repl' },
  type: 'request',
  seq: 13 }
<- evaluateResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 13,
  command: 'evaluate',
  success: true,
  body: { result: 'array(3)', variablesReference: 5 } }
-> variablesRequest
{ command: 'variables',
  arguments: { variablesReference: 1 },
  type: 'request',
  seq: 14 }
<- variablesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 14,
  command: 'variables',
  success: true,
  body: 
   { variables: 
      [ { name: '$anArray',
          value: 'array(3)',
          type: 'array',
          variablesReference: 6 },
        { name: '$arrayWithSpaceKey',
          value: 'uninitialized',
          type: 'uninitialized',
          variablesReference: 0 } ] } }
```
From here on it's an infinite loop until i terminate the server.
VScode keeps requesting variable 5 nonstop and the extension
just returns the original array's contents
```
-> variablesRequest
{ command: 'variables',
  arguments: { variablesReference: 5 },
  type: 'request',
  seq: 15 }
<- variablesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 15,
  command: 'variables',
  success: true,
  body: 
   { variables: 
      [ { name: '0', value: '1', type: 'int', variablesReference: 0 },
        { name: 'test', value: '2', type: 'int', variablesReference: 0 },
        { name: 'test2',
          value: 'array(1)',
          type: 'array',
          variablesReference: 7 } ] } }
-> variablesRequest
{ command: 'variables',
  arguments: { variablesReference: 5 },
  type: 'request',
  seq: 16 }
<- variablesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 16,
  command: 'variables',
  success: true,
  body: 
   { variables: 
      [ { name: '0', value: '1', type: 'int', variablesReference: 0 },
        { name: 'test', value: '2', type: 'int', variablesReference: 0 },
        { name: 'test2',
          value: 'array(1)',
          type: 'array',
          variablesReference: 8 } ] } }
-> variablesRequest
{ command: 'variables',
  arguments: { variablesReference: 5 },
  type: 'request',
  seq: 17 }
<- variablesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 17,
  command: 'variables',
  success: true,
  body: 
   { variables: 
      [ { name: '0', value: '1', type: 'int', variablesReference: 0 },
        { name: 'test', value: '2', type: 'int', variablesReference: 0 },
        { name: 'test2',
          value: 'array(1)',
          type: 'array',
          variablesReference: 9 } ] } }
-> variablesRequest
{ command: 'variables',
  arguments: { variablesReference: 5 },
  type: 'request',
  seq: 18 }
<- variablesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 18,
  command: 'variables',
  success: true,
  body: 
   { variables: 
      [ { name: '0', value: '1', type: 'int', variablesReference: 0 },
        { name: 'test', value: '2', type: 'int', variablesReference: 0 },
        { name: 'test2',
          value: 'array(1)',
          type: 'array',
          variablesReference: 10 } ] } }
```

**Comment by QwertyZW** [comment] 2017-04-01 21:35
[This a dump of devtools console for the whole session](https://github.com/felixfbecker/vscode-php-debug/files/887999/dev.txt)

**Comment by QwertyZW** [comment] 2017-04-01 23:55
@felixfbecker I have a couple more issues, one of which I feel is core, I'd like to share with you but [this](https://github.com/Microsoft/vscode/issues/2163) is not worth the effort

**Comment by cqcwillard** [comment] 2017-04-11 15:49
I had the same issue; I changed my settings to the following with success:

```
"xdebugSettings": {
  "max_children": 50,
  "max_depth": 5
}
```

**Comment by zobo** [comment] 2021-05-10 09:11
This can be controlled with the settings mentioned above. But as of writing dynamically fetching the resto of the data is not possible due to Xdebug limitations. I intend to work on this with Derick and in context of other tasks. Will close this.

**Closed by zobo** 2021-05-10 09:11 UTC
Labels: as designed
