### ISSUE TITLE
Debugging CLI programs with blocking calls block all other php programs in the machine

### ISSUE THREAD

**Issue by watertree** [xdebug/vscode-php-debug#27] opened 2016-03-15 19:39 UTC
To reproduce, in this example, first you can just run this in a bash shell and it will spawn a php interpreter every second:

`while true; do php -r 'echo "ping ";'; date; sleep 1; done`

Try to debug a trivial php cli script with a blocking call (socket reads or sleep calls for example).  For example, if a breakpoint is set in the sleep call in below, the output from the snippet above will keep printing every second.  But while it is sleeping for the 10 seconds or blocking for any other purpose, all other php scripts in the machine become blocked (it looks like it is because the add-in attempts to listen to all php processes.  When first running vscode, you can see activity from external processes flashing in the "call stack" portion of the debug window).

`<?php
sleep(10);
?>`

I am using vscode on Ubuntu 15.10.

**Comment by felixfbecker** [comment] 2016-03-15 23:07
Do other IDEs like PHPStorm or PHPTools for Visual Studio behave differently?

**Comment by watertree** [comment] 2016-03-16 11:43
I haven't checked on Windows, so I am not sure about Visual Studio, but we have tried with both IntelliJ Ultimate (same thing as PHPStorm) and Eclipse PDT and neither xdebug integrations lock outside interpreters when the process being debugged is in a blocking call.

**Comment by felixfbecker** [comment] 2016-03-16 11:55
I will look into it

**Comment by haringsrob** [comment] 2017-10-17 07:46
In phpstorm you can do the following:
<img width="307" alt="screen shot 2017-10-17 at 09 45 49" src="https://user-images.githubusercontent.com/866743/31652612-facda54e-b31f-11e7-9259-12ac7650dbb7.png">

This is the only way this can work, so maybe something similar is required for this extension.

**Comment by zobo** [comment] 2021-05-09 18:08
I tired to reproduce this with one script waiting in a sleep() call, and other short ones in parallel. I could not reproduce it. This issue is 6 years old, so I'm closing it. Please reopen if you can reproduce it.

**Closed by zobo** 2021-05-09 18:08 UTC
Labels: needs more info
