### ISSUE TITLE
Anybody continuing the development of this extension?

### ISSUE THREAD

**Issue by AnrDaemon** [xdebug/vscode-php-debug#371] opened 2019-08-14 10:46 UTC
Last commit to the repo is from March, and there's just too many bugs that block daily work.

**Comment by augustocdias** [comment] 2019-08-15 13:10
Doesn't look like... There's 25 open pull requests and no comment on most of them

**Comment by zobo** [comment] 2019-09-23 22:00
It's a shame, since this is a top match extension for when people search vscode and php debugging. Wonder if @felixfbecker would take a maintainer to at least comb over open PRs...

**Comment by austenc** [comment] 2020-01-09 18:14
What are people using instead? I keep running into xdebug connection issues. It works, then it doesn't.. 🤔

**Comment by AnrDaemon** [comment] 2020-01-10 07:53
It works reliable only if you keep only one session running. :/

**Comment by zobo** [comment] 2020-01-10 08:20
Hm.. I did not have such cases yet...  How is it unstable, how to reproduce it?

**Comment by AnrDaemon** [comment] 2020-01-10 13:27
If you have 2 or more xDebug connections simultaneously opened in the same VS Code window, it's impossible to switch between them.

**Comment by cjwijtmans** [comment] 2020-03-29 17:11
start an active fork then?

**Comment by AnrDaemon** [comment] 2020-03-29 17:38
Not in a position to do so. Else I would.

It got better with VS Code 1.41+ though (SUDDENLY!). But changing between debugging sessions is still problematic.

**Comment by cjwijtmans** [comment] 2020-03-29 21:28
The only annoyance i had so far is that i get breaks when an exception is being display with no traces then i get another break on the same exception with a trace(if the exception is not caught). So i get two breaks on the same exception unless the exception is caught then i get one break with no stack trace. So why not just get rid of the first break without a stack trace. Not sure what is causing this behavior though.

**Comment by AnrDaemon** [comment] 2020-03-30 07:40
`xdebug.remote_mode = jit` ?
That's how xdebug itself works. Extension is only listening, it can't know ahead of time, what xdebug will send to it.

**Comment by cjwijtmans** [comment] 2020-03-31 00:47
> `xdebug.remote_mode = jit` ?
> That's how xdebug itself works. Extension is only listening, it can't know ahead of time, what xdebug will send to it.

Not what i am saying.  It appears that exception that are caught(later) are breaking with no stack trace. While exceptions that are not caught(later) are breaking once without stack trace and then again with a stack trace... So add an option to only break when there is a stack trace present.

**Comment by AnrDaemon** [comment] 2020-03-31 09:26
Why not disable breaking on caught exceptions?

Sadly it can't be set in `"xdebugSettings": {…}`.

**Comment by Vaggal** [comment] 2021-09-16 12:04
Why is this issue still open? The development is continuing and the latest comments are related to a different issue.

**Comment by zobo** [comment] 2021-09-16 13:06
I agree, reports here went into a different direction. Please open a new specific issue if you still have it.
Closing this as solved, since I'm continuing development :)

**Closed by zobo** 2021-09-16 13:06 UTC
