### ISSUE TITLE
opening same file twice at breakpoint

### ISSUE THREAD

**Issue by nvkokorin** [xdebug/vscode-php-debug#382] opened 2019-12-06 06:55 UTC
PHP version:  7.3.12
XDebug version:  2.8.0
Adapter version: 1.13.0

Your launch.json:  default
XDebug php.ini config: default

How to reproduce:
1. create a folder contains symbolic link or directory junction (created with mklink) points to some folder with php sources;
2. open this folder in VSCode;
3. open some php under symbolic link to edit (tab's hint will be show the linked path);
4. set a breakpoint and start debug session;
5. start php server or apache if not started, do some request from browser as usual;
6. executing is stops at breakpoint but will be opened a new tab with same file (tab's hint will be show the **physical** path of file);
7. as result we see two same files but opened from different location.

VSCode info
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.15063

**Comment by gwharton** [comment] 2020-10-04 11:42
I get this on vscode with php xdebug but its not related to sybmolic links for me. It is more to do with a mismatch between relative and absolute paths.

I am using RemoteWSL

My launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log": false,
            "pathMappings": {
                "/home/ubuntu/www": "${workspaceRoot:www}"
            },
            "xdebugSettings": {
                "max_children": 128,
                "max_data": 512,
                "max_depth": 3,
                "show_hidden": true
            }
        }
    ]
}
```

/home/ubuntu/www is project root

www is added as a workspace folder inside my workspace

Placing a breakpoint results in the following path in the debug screen. Not the relative path.

![image](https://user-images.githubusercontent.com/30697781/95014322-f8179980-063d-11eb-8cec-32299c04a730.png)

The full path to this file is /home/ubuntu/www/app/code/Gw/RichSnippets/Block/Snippets.php

Here is the breakpoint set in the file, and the file tab

![image](https://user-images.githubusercontent.com/30697781/95014349-1e3d3980-063e-11eb-917d-ba87a2ff1391.png)

Now if I run the app and break on the breakpoint, it opens up a second copy of the file. Looking at the file tabs, the original file has a relative path, and the new file has a full path.

![image](https://user-images.githubusercontent.com/30697781/95014372-4dec4180-063e-11eb-9fa8-ab603a8761ce.png)

It has halted on the correct line in the file, but the breakpoint marker is not there, as this file has the full path in the file tab. So it would appear that VScode got an instruction to load the file with the full path and did not realise the same file with the relative path is already open, and opened up a new copy.

This only seems to have started recently.

**Comment by bseddon** [comment] 2020-12-22 20:10
I also see a problem debugging a project where a junction is used in a script being debugged using CLI so the issue of alternative hosts and query paths does not arise.  However, I don't think it is a problem with this extension. 

In my case, a junction is used to include and debug common scripts used in several projects.  Only scripts within the folders included via a junction are affected.  The path of the script that appears in the debug window is the 'original' path not the path created via the junction.  

It doesn't matter if the script ('program') specified in the configuration is within the folders joined by the junction  or not, as long as the breakpoint is then the file shown in the debugger is from the 'original' folder regardless of the location of the script specified in the configuration.

Much as it is convenient to want PHP Debug to be the source of the error, reviewing the extension typescript code, its hard to see how the extension can be the source of the problem.  The extension only seems to be responsible for computing a set of parameters - including the script to debug - that are passed to the VSCode debugger infrastructure to spawn a process - based on php.exe in this case.

Instead it is the the responsibility of VS Code to pass break point and file information to the debug process so XDebug is able to act on them.

This issue occurs when using PHP 7.4.13 or 8.0 with XDebug 3.x or PHP 7.2.6 with XDebug 2.x. This behaviour does **not** occur with the same code, same folders, same PHP executable and same ini file when they are used in Eclipse.   This is another indication the issue is with VS Code.  

Now to find out how raise an issue with VS Code...

**Comment by bseddon** [comment] 2020-12-23 01:02
@felixfbecker I have tried to report this issue on the [VS Code github repository](https://github.com/microsoft/vscode/issues/113320). There I have provided an explanation of what I think is happening and why I believe its VS Code issue.  However, it's been summarily rejected referring me to you.  Maybe you will have more success unless you know it is a problem with PHP Debug.  I know its not a big deal since there is a work around but it seems VS Code ought to be corrected at some point.

**Comment by sshxmz** [comment] 2021-01-14 02:00
Also happened for me. The problem disappears when I uninstall this extension.

**Comment by bseddon** [comment] 2021-01-14 02:08
Yes, of course the problem will go away if the extension is removed.  If it's removed then VS code never sends the wrong path to the extension.  However if it's removed you can't debug PHP which is a bit of a limitation when writing PHP scripts.

**Comment by zobo** [comment] 2022-05-20 12:31
If it can't be fixed with path mapping that there is nothing this extension can do. Please reopen if this is still an issue.

**Closed by zobo** 2022-05-20 12:31 UTC

**Comment by kesavanm** [comment] 2024-03-07 04:24
Confirming this issue on :
```
PHP Version: 8.3.3-1+ubuntu20.04.1+deb.sury.org+1
Server Software: Apache/2.4.41 (Ubuntu)
Using Xdebug version: 3.3.1
```
`pathMappings`  acts as workaround. 


```ini

          "pathMappings": {
                "/mnt/16b5a806-1ad0-41fc-8bd6-a16fe6XXXXX/var/www/html/test/": "${workspaceRoot}",
            },
```

No issue on PHP-7x with xDebug-2X
